Core: Trocando forma de direcionamento da saída de erro de "/dev/stderr" para ">&2".

diff --git a/funcoeszz b/funcoeszz
--- a/funcoeszz
+++ b/funcoeszz
@@ -135,7 +135,12 @@ zztool ()
 	case "$ferramenta" in
 		uso)
 			# Extrai a mensagem de uso da função $1, usando seu --help
-			zzzz -h "$1" -h | grep Uso
+			if test $erro -eq 1
+			then
+				zzzz -h "$1" -h | grep Uso >&2
+			else
+				zzzz -h "$1" -h | grep Uso
+			fi
 		;;
 		eco)
 			# Mostra mensagem colorida caso $ZZCOR esteja ligada
@@ -148,7 +153,7 @@ zztool ()
 		;;
 		erro)
 			# Mensagem de erro
-			printf "%b\n" "$*" > /dev/stderr
+			printf "%b\n" "$*" >&2
 		;;
 		acha)
 			# Destaca o padrão $1 no texto via STDIN ou $2
@@ -184,7 +189,7 @@ zztool ()
 			# Verifica se o nome de arquivo informado está vago
 			if test -e "$1"
 			then
-				echo "Arquivo $1 já existe. Abortando." > /dev/stderr
+				echo "Arquivo $1 já existe. Abortando." >&2
 				return 1
 			fi
 		;;
@@ -192,7 +197,7 @@ zztool ()
 			# Verifica se o arquivo existe e é legível
 			if ! test -r "$1"
 			then
-				echo "Não consegui ler o arquivo $1" > /dev/stderr
+				echo "Não consegui ler o arquivo $1" >&2
 				return 1
 			fi
 
@@ -218,7 +223,7 @@ zztool ()
 			# Ano maior que 9999 pesa no processamento
 			echo "$1" | grep -v '^00*$' | grep '^[0-9]\{1,4\}$' >/dev/null && return 0
 
-			test -n "$erro" && echo "Ano inválido '$1'" > /dev/stderr
+			test -n "$erro" && echo "Ano inválido '$1'" >&2
 			return 1
 		;;
 		testa_ano_bissexto)
@@ -235,14 +240,14 @@ zztool ()
 			test $((y%4)) -eq 0 && test $((y%100)) -ne 0 || test $((y%400)) -eq 0
 			test $? -eq 0 && return 0
 
-			test -n "$erro" && echo "Ano bissexto inválido '$1'" > /dev/stderr
+			test -n "$erro" && echo "Ano bissexto inválido '$1'" >&2
 			return 1
 		;;
 		testa_numero)
 			# Testa se $1 é um número positivo
 			echo "$1" | grep '^[0-9]\{1,\}$' >/dev/null && return 0
 
-			test -n "$erro" && echo "Número inválido '$1'" > /dev/stderr
+			test -n "$erro" && echo "Número inválido '$1'" >&2
 			return 1
 
 			# TODO Usar em *todas* as funções que recebem números
@@ -251,7 +256,7 @@ zztool ()
 			# Testa se $1 é um número (pode ter sinal: -2 +2)
 			echo "$1" | grep '^[+-]\{0,1\}[0-9]\{1,\}$' >/dev/null && return 0
 
-			test -n "$erro" && echo "Número inválido '$1'" > /dev/stderr
+			test -n "$erro" && echo "Número inválido '$1'" >&2
 			return 1
 		;;
 		testa_numero_fracionario)
@@ -259,7 +264,7 @@ zztool ()
 			# regex: \d+[,.]\d+
 			echo "$1" | grep '^[0-9]\{1,\}[,.][0-9]\{1,\}$' >/dev/null && return 0
 
-			test -n "$erro" && echo "Número inválido '$1'" > /dev/stderr
+			test -n "$erro" && echo "Número inválido '$1'" >&2
 			return 1
 		;;
 		testa_dinheiro)
@@ -267,14 +272,14 @@ zztool ()
 			# regex: (  \d{1,3}(\.\d\d\d)+  |  \d+  ),\d\d
 			echo "$1" | grep '^\([0-9]\{1,3\}\(\.[0-9][0-9][0-9]\)\{1,\}\|[0-9]\{1,\}\),[0-9][0-9]$' >/dev/null && return 0
 
-			test -n "$erro" && echo "Valor inválido '$1'" > /dev/stderr
+			test -n "$erro" && echo "Valor inválido '$1'" >&2
 			return 1
 		;;
 		testa_binario)
 			# Testa se $1 é um número binário
 			echo "$1" | grep '^[01]\{1,\}$' >/dev/null && return 0
 
-			test -n "$erro" && echo "Número binário inválido '$1'" > /dev/stderr
+			test -n "$erro" && echo "Número binário inválido '$1'" >&2
 			return 1
 		;;
 		testa_ip)
@@ -282,7 +287,7 @@ zztool ()
 			local nnn="\([0-9]\{1,2\}\|1[0-9][0-9]\|2[0-4][0-9]\|25[0-5]\)" # 0-255
 			echo "$1" | grep "^$nnn\.$nnn\.$nnn\.$nnn$" >/dev/null && return 0
 
-			test -n "$erro" && echo "Número IP inválido '$1'" > /dev/stderr
+			test -n "$erro" && echo "Número IP inválido '$1'" >&2
 			return 1
 		;;
 		testa_data)
@@ -292,14 +297,14 @@ zztool ()
 			local d31='31/\(0[13578]\|1[02]\)'
 			echo "$1" | grep "^\($d29\|$d30\|$d31\)/[0-9]\{1,4\}$" >/dev/null && return 0
 
-			test -n "$erro" && echo "Data inválida '$1', deve ser dd/mm/aaaa" > /dev/stderr
+			test -n "$erro" && echo "Data inválida '$1', deve ser dd/mm/aaaa" >&2
 			return 1
 		;;
 		testa_hora)
 			# Testa se $1 é uma hora (hh:mm)
 			echo "$1" | grep "^\(0\{0,1\}[0-9]\|1[0-9]\|2[0-3]\):[0-5][0-9]$" >/dev/null && return 0
 
-			test -n "$erro" && echo "Hora inválida '$1'" > /dev/stderr
+			test -n "$erro" && echo "Hora inválida '$1'" >&2
 			return 1
 		;;
 		multi_stdin)
