zztool: Usando shift já no início, para que os argumentos das ferramentas sejam $1, $2, $3... Antes eles eram $2, $3, $4... pois o $1 era o nome da ferramenta.

diff --git a/funcoeszz b/funcoeszz
--- a/funcoeszz
+++ b/funcoeszz
@@ -108,13 +108,17 @@ unset ZZCOR_DFT ZZPATH_DFT ZZDIR_DFT ZZTMPDIR_DFT
 # ----------------------------------------------------------------------------
 zztool ()
 {
-	case "$1" in
+	local ferramenta="$1"
+	
+	# Remove nome da ferramenta, assim $1 é o primeiro argumento
+	shift
+	
+	case "$ferramenta" in
 		uso)
-			# Extrai a mensagem de uso da função $2, usando seu --help
-			zzzz -h $2 -h | grep Uso
+			# Extrai a mensagem de uso da função $1, usando seu --help
+			zzzz -h $1 -h | grep Uso
 		;;
 		eco)
-			shift
 			# Mostra mensagem colorida caso $ZZCOR esteja ligada
 			if [ "$ZZCOR" != '1' ]
 			then
@@ -124,11 +128,11 @@ zztool ()
 			fi
 		;;
 		acha)
-			# Destaca o padrão $2 no texto via STDIN ou $3
+			# Destaca o padrão $1 no texto via STDIN ou $2
 			# O padrão pode ser uma regex no formato BRE (grep/sed)
 			local esc=$(printf '\033')
-			local padrao=$(echo "$2" | sed 's,/,\\/,g') # escapa /
-			shift; shift
+			local padrao=$(echo "$1" | sed 's,/,\\/,g') # escapa /
+			shift
 			zztool multi_stdin "$@" |
 				if [ "$ZZCOR" != '1' ]
 				then
@@ -138,13 +142,13 @@ zztool ()
 				fi
 		;;
 		grep_var)
-			# $2 está presente em $3?
-			test "${3#*$2}" != "$3"
+			# $1 está presente em $2?
+			test "${2#*$1}" != "$2"
 		;;
 		index_var)
-			# $2 está em qual posição em $3?
-			local padrao="$2"
-			local texto="$3"
+			# $1 está em qual posição em $2?
+			local padrao="$1"
+			local texto="$2"
 			if zztool grep_var "$padrao" "$texto"
 			then
 				texto="${texto%%$padrao*}"
@@ -155,17 +159,17 @@ zztool ()
 		;;
 		arquivo_vago)
 			# Verifica se o nome de arquivo informado está vago
-			if test -e "$2"
+			if test -e "$1"
 			then
-				echo "Arquivo $2 já existe. Abortando."
+				echo "Arquivo $1 já existe. Abortando."
 				return 1
 			fi
 		;;
 		arquivo_legivel)
 			# Verifica se o arquivo existe e é legível
-			if ! test -r "$2"
+			if ! test -r "$1"
 			then
-				echo "Não consegui ler o arquivo $2"
+				echo "Não consegui ler o arquivo $1"
 				return 1
 			fi
 			
@@ -173,18 +177,17 @@ zztool ()
 		;;
 		num_linhas)
 			# Informa o número de linhas, sem formatação 
-			shift
 			zztool file_stdin "$@" |
 				wc -l |
 				tr -d ' \t'
 		;;
 		testa_ano)
-			# Testa se $2 é um ano válido: 0-9999
+			# Testa se $1 é um ano válido: 0-9999
 			# Ano maior que 9999 pesa no processamento
-			echo "$2" | grep '^[0-9]\{1,4\}$' >/dev/null
+			echo "$1" | grep '^[0-9]\{1,4\}$' >/dev/null
 		;;
 		testa_ano_bissexto)
-			# Testa se $2 é um ano bissexto
+			# Testa se $1 é um ano bissexto
 			#
 			# A year is a leap year if it is evenly divisible by 4
 			# ...but not if it's evenly divisible by 100
@@ -193,48 +196,48 @@ zztool ()
 			# http://www.delorie.com/gnu/docs/gcal/gcal_34.html
 			# http://en.wikipedia.org/wiki/Leap_year
 			#
-			local y=$2
+			local y=$1
 			[ $((y%4)) -eq 0 ] && [ $((y%100)) -ne 0 ] || [ $((y%400)) -eq 0 ]
 		;;
 		testa_numero)
-			# Testa se $2 é um número positivo
-			echo "$2" | grep '^[0-9]\{1,\}$' >/dev/null
+			# Testa se $1 é um número positivo
+			echo "$1" | grep '^[0-9]\{1,\}$' >/dev/null
 			
 			# TODO Usar em *todas* as funções que recebem números
 		;;
 		testa_numero_sinal)
-			# Testa se $2 é um número (pode ter sinal: -2 +2)
-			echo "$2" | grep '^[+-]\{0,1\}[0-9]\{1,\}$' >/dev/null
+			# Testa se $1 é um número (pode ter sinal: -2 +2)
+			echo "$1" | grep '^[+-]\{0,1\}[0-9]\{1,\}$' >/dev/null
 		;;
 		testa_numero_fracionario)
-			# Testa se $2 é um número fracionário (1.234 ou 1,234)
+			# Testa se $1 é um número fracionário (1.234 ou 1,234)
 			# regex: \d+[,.]\d+
-			echo "$2" | grep '^[0-9]\{1,\}[,.][0-9]\{1,\}$' >/dev/null
+			echo "$1" | grep '^[0-9]\{1,\}[,.][0-9]\{1,\}$' >/dev/null
 		;;
 		testa_dinheiro)
-			# Testa se $2 é um valor monetário (1.234,56 ou 1234,56)
+			# Testa se $1 é um valor monetário (1.234,56 ou 1234,56)
 			# regex: (  \d{1,3}(\.\d\d\d)+  |  \d+  ),\d\d
-			echo "$2" | grep '^\([0-9]\{1,3\}\(\.[0-9][0-9][0-9]\)\{1,\}\|[0-9]\{1,\}\),[0-9][0-9]$' >/dev/null
+			echo "$1" | grep '^\([0-9]\{1,3\}\(\.[0-9][0-9][0-9]\)\{1,\}\|[0-9]\{1,\}\),[0-9][0-9]$' >/dev/null
 		;;
 		testa_binario)
-			# Testa se $2 é um número binário
-			echo "$2" | grep '^[01]\{1,\}$' >/dev/null
+			# Testa se $1 é um número binário
+			echo "$1" | grep '^[01]\{1,\}$' >/dev/null
 		;;
 		testa_ip)
-			# Testa se $2 é um número IP (nnn.nnn.nnn.nnn)
+			# Testa se $1 é um número IP (nnn.nnn.nnn.nnn)
 			local nnn="\([0-9]\{1,2\}\|1[0-9][0-9]\|2[0-4][0-9]\|25[0-5]\)" # 0-255
-			echo "$2" | grep "^$nnn\.$nnn\.$nnn\.$nnn$" >/dev/null
+			echo "$1" | grep "^$nnn\.$nnn\.$nnn\.$nnn$" >/dev/null
 		;;
 		testa_data)
-			# Testa se $2 é uma data (dd/mm/aaaa)
+			# Testa se $1 é uma data (dd/mm/aaaa)
 			local d29='\(0[1-9]\|[12][0-9]\)/\(0[1-9]\|1[012]\)'
 			local d30='30/\(0[13-9]\|1[012]\)'
 			local d31='31/\(0[13578]\|1[02]\)'
-			echo "$2" | grep "^\($d29\|$d30\|$d31\)/[0-9]\{1,4\}$" >/dev/null
+			echo "$1" | grep "^\($d29\|$d30\|$d31\)/[0-9]\{1,4\}$" >/dev/null
 		;;
 		testa_hora)
-			# Testa se $2 é uma hora (hh:mm)
-			echo "$2" | grep "^\(0\{0,1\}[0-9]\|1[0-9]\|2[0-3]\):[0-5][0-9]$" >/dev/null
+			# Testa se $1 é uma hora (hh:mm)
+			echo "$1" | grep "^\(0\{0,1\}[0-9]\|1[0-9]\|2[0-3]\):[0-5][0-9]$" >/dev/null
 		;;
 		multi_stdin)
 			# Mostra na tela os argumentos *ou* a STDIN, nesta ordem
@@ -242,7 +245,7 @@ zztool ()
 			#     echo texto | funcao
 			# ou
 			#     funcao texto
-			shift
+
 			if [ "$1" ]
 			then
 				echo "$*"
@@ -256,7 +259,7 @@ zztool ()
 			#     cat arquivo | funcao
 			# ou
 			#     funcao arquivo
-			shift
+
 			sed -n p "$@"  # comando nulo, simula um cat
 		;;
 		list2lines)
@@ -275,7 +278,6 @@ zztool ()
 				sed 's/^ // ; s/ $//'
 		;;
 		trim)
-			shift
 			zztool multi_stdin "$@" |
 		 		sed 's/^[[:blank:]]*// ; s/[[:blank:]]*$//'
 		;;
@@ -284,7 +286,7 @@ zztool ()
 			# Números e $ não são alterados, resto fica /entre barras/
 			#     foo     -> /foo/
 			#     foo/bar -> /foo\/bar/
-			shift
+			
 			local texto="$*"
 			
 			if zztool testa_numero "$texto" || test "$texto" = '$'
