manpage & website atualizados

diff --git a/web/online/funcoeszz b/web/online/funcoeszz
--- a/web/online/funcoeszz
+++ b/web/online/funcoeszz
@@ -108,13 +108,21 @@ unset ZZCOR_DFT ZZPATH_DFT ZZDIR_DFT ZZTMPDIR_DFT
 # ----------------------------------------------------------------------------
 zztool ()
 {
-	case "$1" in
+	local erro ferramenta
+	
+	# Devo mostrar a mensagem de erro?
+	test "$1" = '-e' && erro=1 && shift
+	
+	# Libera o nome da ferramenta do $1
+	ferramenta="$1"
+	shift
+	
+	case "$ferramenta" in
 		uso)
-			# Extrai a mensagem de uso da função $2, usando seu --help
-			zzzz -h $2 -h | grep Uso
+			# Extrai a mensagem de uso da função $1, usando seu --help
+			zzzz -h $1 -h | grep Uso
 		;;
 		eco)
-			shift
 			# Mostra mensagem colorida caso $ZZCOR esteja ligada
 			if [ "$ZZCOR" != '1' ]
 			then
@@ -124,11 +132,11 @@ zztool ()
 			fi
 		;;
 		acha)
-			# Destaca o padrão $2 no texto via STDIN ou $3
+			# Destaca o padrão $1 no texto via STDIN ou $2
 			# O padrão pode ser uma regex no formato BRE (grep/sed)
 			local esc=$(printf '\033')
-			local padrao=$(echo "$2" | sed 's,/,\\/,g') # escapa /
-			shift; shift
+			local padrao=$(echo "$1" | sed 's,/,\\/,g') # escapa /
+			shift
 			zztool multi_stdin "$@" |
 				if [ "$ZZCOR" != '1' ]
 				then
@@ -138,13 +146,13 @@ zztool ()
 				fi
 		;;
 		grep_var)
-			# $2 está presente em $3?
-			test "${3#*$2}" != "$3"
+			# $1 está presente em $2?
+			test "${2#*$1}" != "$2"
 		;;
 		index_var)
-			# $2 está em qual posição em $3?
-			local padrao="$2"
-			local texto="$3"
+			# $1 está em qual posição em $2?
+			local padrao="$1"
+			local texto="$2"
 			if zztool grep_var "$padrao" "$texto"
 			then
 				texto="${texto%%$padrao*}"
@@ -155,17 +163,17 @@ zztool ()
 		;;
 		arquivo_vago)
 			# Verifica se o nome de arquivo informado está vago
-			if test -e "$2"
+			if test -e "$1"
 			then
-				echo "Arquivo $2 já existe. Abortando."
+				echo "Arquivo $1 já existe. Abortando."
 				return 1
 			fi
 		;;
 		arquivo_legivel)
 			# Verifica se o arquivo existe e é legível
-			if ! test -r "$2"
+			if ! test -r "$1"
 			then
-				echo "Não consegui ler o arquivo $2"
+				echo "Não consegui ler o arquivo $1"
 				return 1
 			fi
 			
@@ -173,18 +181,20 @@ zztool ()
 		;;
 		num_linhas)
 			# Informa o número de linhas, sem formatação 
-			shift
 			zztool file_stdin "$@" |
 				wc -l |
 				tr -d ' \t'
 		;;
 		testa_ano)
-			# Testa se $2 é um ano válido: 0-9999
+			# Testa se $1 é um ano válido: 0-9999
 			# Ano maior que 9999 pesa no processamento
-			echo "$2" | grep '^[0-9]\{1,4\}$' >/dev/null
+			echo "$1" | grep '^[0-9]\{1,4\}$' >/dev/null && return 0
+
+			test -n "$erro" && echo "Ano inválido '$1'"
+			return 1
 		;;
 		testa_ano_bissexto)
-			# Testa se $2 é um ano bissexto
+			# Testa se $1 é um ano bissexto
 			#
 			# A year is a leap year if it is evenly divisible by 4
 			# ...but not if it's evenly divisible by 100
@@ -193,48 +203,76 @@ zztool ()
 			# http://www.delorie.com/gnu/docs/gcal/gcal_34.html
 			# http://en.wikipedia.org/wiki/Leap_year
 			#
-			local y=$2
+			local y=$1
 			[ $((y%4)) -eq 0 ] && [ $((y%100)) -ne 0 ] || [ $((y%400)) -eq 0 ]
+			test $? -eq 0 && return 0
+
+			test -n "$erro" && echo "Ano bissexto inválido '$1'"
+			return 1
 		;;
 		testa_numero)
-			# Testa se $2 é um número positivo
-			echo "$2" | grep '^[0-9]\{1,\}$' >/dev/null
-			
+			# Testa se $1 é um número positivo
+			echo "$1" | grep '^[0-9]\{1,\}$' >/dev/null && return 0
+
+			test -n "$erro" && echo "Número inválido '$1'"
+			return 1
+
 			# TODO Usar em *todas* as funções que recebem números
 		;;
 		testa_numero_sinal)
-			# Testa se $2 é um número (pode ter sinal: -2 +2)
-			echo "$2" | grep '^[+-]\{0,1\}[0-9]\{1,\}$' >/dev/null
+			# Testa se $1 é um número (pode ter sinal: -2 +2)
+			echo "$1" | grep '^[+-]\{0,1\}[0-9]\{1,\}$' >/dev/null && return 0
+
+			test -n "$erro" && echo "Número inválido '$1'"
+			return 1
 		;;
 		testa_numero_fracionario)
-			# Testa se $2 é um número fracionário (1.234 ou 1,234)
+			# Testa se $1 é um número fracionário (1.234 ou 1,234)
 			# regex: \d+[,.]\d+
-			echo "$2" | grep '^[0-9]\{1,\}[,.][0-9]\{1,\}$' >/dev/null
+			echo "$1" | grep '^[0-9]\{1,\}[,.][0-9]\{1,\}$' >/dev/null && return 0
+
+			test -n "$erro" && echo "Número inválido '$1'"
+			return 1
 		;;
 		testa_dinheiro)
-			# Testa se $2 é um valor monetário (1.234,56 ou 1234,56)
+			# Testa se $1 é um valor monetário (1.234,56 ou 1234,56)
 			# regex: (  \d{1,3}(\.\d\d\d)+  |  \d+  ),\d\d
-			echo "$2" | grep '^\([0-9]\{1,3\}\(\.[0-9][0-9][0-9]\)\{1,\}\|[0-9]\{1,\}\),[0-9][0-9]$' >/dev/null
+			echo "$1" | grep '^\([0-9]\{1,3\}\(\.[0-9][0-9][0-9]\)\{1,\}\|[0-9]\{1,\}\),[0-9][0-9]$' >/dev/null && return 0
+
+			test -n "$erro" && echo "Valor inválido '$1'"
+			return 1
 		;;
 		testa_binario)
-			# Testa se $2 é um número binário
-			echo "$2" | grep '^[01]\{1,\}$' >/dev/null
+			# Testa se $1 é um número binário
+			echo "$1" | grep '^[01]\{1,\}$' >/dev/null && return 0
+
+			test -n "$erro" && echo "Número binário inválido '$1'"
+			return 1
 		;;
 		testa_ip)
-			# Testa se $2 é um número IP (nnn.nnn.nnn.nnn)
+			# Testa se $1 é um número IP (nnn.nnn.nnn.nnn)
 			local nnn="\([0-9]\{1,2\}\|1[0-9][0-9]\|2[0-4][0-9]\|25[0-5]\)" # 0-255
-			echo "$2" | grep "^$nnn\.$nnn\.$nnn\.$nnn$" >/dev/null
+			echo "$1" | grep "^$nnn\.$nnn\.$nnn\.$nnn$" >/dev/null && return 0
+
+			test -n "$erro" && echo "Número IP inválido '$1'"
+			return 1
 		;;
 		testa_data)
-			# Testa se $2 é uma data (dd/mm/aaaa)
+			# Testa se $1 é uma data (dd/mm/aaaa)
 			local d29='\(0[1-9]\|[12][0-9]\)/\(0[1-9]\|1[012]\)'
 			local d30='30/\(0[13-9]\|1[012]\)'
 			local d31='31/\(0[13578]\|1[02]\)'
-			echo "$2" | grep "^\($d29\|$d30\|$d31\)/[0-9]\{1,4\}$" >/dev/null
+			echo "$1" | grep "^\($d29\|$d30\|$d31\)/[0-9]\{1,4\}$" >/dev/null && return 0		
+
+			test -n "$erro" && echo "Data inválida '$1', deve ser dd/mm/aaaa"
+			return 1
 		;;
 		testa_hora)
-			# Testa se $2 é uma hora (hh:mm)
-			echo "$2" | grep "^\(0\{0,1\}[0-9]\|1[0-9]\|2[0-3]\):[0-5][0-9]$" >/dev/null
+			# Testa se $1 é uma hora (hh:mm)
+			echo "$1" | grep "^\(0\{0,1\}[0-9]\|1[0-9]\|2[0-3]\):[0-5][0-9]$" >/dev/null && return 0
+
+			test -n "$erro" && echo "Hora inválida '$1'"
+			return 1
 		;;
 		multi_stdin)
 			# Mostra na tela os argumentos *ou* a STDIN, nesta ordem
@@ -242,7 +280,7 @@ zztool ()
 			#     echo texto | funcao
 			# ou
 			#     funcao texto
-			shift
+
 			if [ "$1" ]
 			then
 				echo "$*"
@@ -256,8 +294,8 @@ zztool ()
 			#     cat arquivo | funcao
 			# ou
 			#     funcao arquivo
-			shift
-			sed -n p "$@"  # comando nulo, simula um cat
+
+			cat "${@:--}"  # Traduzindo: cat $@ ou cat -
 		;;
 		list2lines)
 			# Limpa lista da STDIN e retorna um item por linha
@@ -275,7 +313,6 @@ zztool ()
 				sed 's/^ // ; s/ $//'
 		;;
 		trim)
-			shift
 			zztool multi_stdin "$@" |
 		 		sed 's/^[[:blank:]]*// ; s/[[:blank:]]*$//'
 		;;
@@ -284,7 +321,7 @@ zztool ()
 			# Números e $ não são alterados, resto fica /entre barras/
 			#     foo     -> /foo/
 			#     foo/bar -> /foo\/bar/
-			shift
+			
 			local texto="$*"
 			
 			if zztool testa_numero "$texto" || test "$texto" = '$'
@@ -1089,6 +1126,39 @@ zzascii ()
 	done
 }
 # ----------------------------------------------------------------------------
+# zzbissexto
+# Diz se o ano informado é bissexto ou não.
+# Obs.: Se o ano não for informado, usa o atual.
+# Uso: zzbissexto [ano]
+# Ex.: zzbissexto
+#      zzbissexto 2000
+#
+# Autor: Aurélio Marinho Jargas, www.aurelio.net
+# Desde: 2011-05-21
+# Versão: 1
+# Licença: GPL
+# Tags: data
+# ----------------------------------------------------------------------------
+zzbissexto ()
+{
+	zzzz -h bissexto $1 && return
+
+	local ano="$1"
+
+	# Se o ano não for informado, usa o atual
+	test -z "$ano" && ano=$(date +%Y)
+
+	# Validação
+	zztool -e testa_ano $ano || return 1
+
+	if zztool testa_ano_bissexto $ano
+	then
+		echo $ano é bissexto
+	else
+		echo $ano não é bissexto
+	fi
+}
+# ----------------------------------------------------------------------------
 # zzbyte
 # Conversão entre grandezas de bytes (mega, giga, tera, etc).
 # Uso: zzbyte N [unidade-entrada] [unidade-saida]  # BKMGTPEZY
@@ -1359,6 +1429,7 @@ zzcalculaip ()
 # Desde: 2008-10-23
 # Licença: GPL
 # Requisitos: zzdata zzpascoa
+# Tags: data
 # ----------------------------------------------------------------------------
 zzcarnaval ()
 {
@@ -1369,13 +1440,9 @@ zzcarnaval ()
 	# Se o ano não for informado, usa o atual
 	test -z "$ano" && ano=$(date +%Y)
 
-	# Verificação básica
-	if ! zztool testa_ano $ano
-	then
-		echo "Ano inválido '$ano'"
-		return 1
-	fi
-
+	# Validação
+	zztool -e testa_ano $ano || return 1
+	
 	# Ah, como é fácil quando se tem as ferramentas certas ;)
 	zzdata $(zzpascoa $ano) - 47
 }
@@ -1486,6 +1553,7 @@ zzcnpj ()
 # Uso: zzcontapalavra [-i|-p] palavra arquivo(s)
 # Ex.: zzcontapalavra root /etc/passwd
 #      zzcontapalavra -i -p a /etc/passwd      # Compare com grep -ci a
+#      cat /etc/passwd | zzcontapalavra root
 #
 # Autor: Aurélio Marinho Jargas, www.aurelio.net
 # Desde: 2003-10-02
@@ -1518,7 +1586,8 @@ zzcontapalavra ()
 	# Contorna a limitação do grep -c pesquisando pela palavra
 	# e quebrando o resultado em uma palavra por linha (tr).
 	# Então pode-se usar o grep -c para contar.
-	grep -h ${ignora:+-i} ${inteira:+-w} -- "$padrao" "$@" |
+	zztool file_stdin "$@" |
+		grep -h ${ignora:+-i} ${inteira:+-w} -- "$padrao" |
 		tr '\t./ -,:-@[-_{-~' '\n' |
 		grep -c ${ignora:+-i} ${inteira:+-w} -- "$padrao"
 }
@@ -1709,6 +1778,7 @@ zzconverte ()
 # Desde: 2008-11-21
 # Licença: GPL
 # Requisitos: zzdata zzpascoa
+# Tags: data
 # ----------------------------------------------------------------------------
 zzcorpuschristi ()
 {
@@ -1719,12 +1789,8 @@ zzcorpuschristi ()
 	# Se o ano não for informado, usa o atual
 	test -z "$ano" && ano=$(date +%Y)
 
-	# Verificação básica
-	if ! zztool testa_ano $ano
-	then
-		echo "Ano inválido '$ano'"
-		return 1
-	fi
+	# Validação
+	zztool -e testa_ano $ano || return 1
 
 	# Ah, como é fácil quando se tem as ferramentas certas ;)
 	# e quando já temos o código e só precisamos mudar os numeros
@@ -1884,6 +1950,7 @@ zzcpf ()
 # Desde: 2003-02-07
 # Versão: 4
 # Licença: GPL
+# Tags: data, cálculo
 # ----------------------------------------------------------------------------
 zzdata ()
 {
@@ -1961,12 +2028,8 @@ zzdata ()
 				ddmm="${valor%/*}"
 
 				# Data em formato válido?
-				if ! zztool testa_data "$valor"
-				then
-					echo "Data inválida '$valor', deve ser dd/mm/aaaa"
-					return 1
-				fi
-
+				zztool -e testa_data "$valor" || return 1
+				
 				# 29/02 em um ano não-bissexto?
 				if test "$ddmm" = '29/02' && ! zztool testa_ano_bissexto "$yyyy"
 				then
@@ -2389,6 +2452,7 @@ zzdata ()
 # Versão: 3
 # Licença: GPL
 # Requisitos: zzdata
+# Tags: data
 # ----------------------------------------------------------------------------
 zzdiadasemana ()
 {
@@ -2414,12 +2478,8 @@ zzdiadasemana ()
 	# Se a data não foi informada, usa a atual
 	test -z "$data" && data=$(date +%d/%m/%Y)
 
-	# Valida o formato da data
-	if ! zztool testa_data "$data"
-	then
-		echo "Data inválida '$data', deve ser dd/mm/aaaa"
-		return 1
-	fi
+	# Validação
+	zztool -e testa_data "$data" || return 1
 
 	# O cálculo se baseia na data ZERO (01/01/1970), que é quinta-feira.
 	# Basta dividir o delta (intervalo de dias até a data ZERO) por 7.
@@ -2453,6 +2513,7 @@ zzdiadasemana ()
 # Versão: 1
 # Licença: GPL
 # Requisitos: zzdata zzdiadasemana
+# Tags: data, cálculo
 # ----------------------------------------------------------------------------
 zzdiasuteis ()
 {
@@ -2472,14 +2533,8 @@ zzdiasuteis ()
 	fi
 
 	# Valida o formato das datas
-	for data in $data1 $data2
-	do
-		if ! zztool testa_data "$data"
-		then
-			echo "Data inválida '$data', deve ser dd/mm/aaaa"
-			return 1
-		fi
-	done
+	zztool -e testa_data "$data1" || return 1
+	zztool -e testa_data "$data2" || return 1
 
 	# Quantos dias há entre as duas datas?
 	dias=$(zzdata $data2 - $data1)
@@ -2933,6 +2988,7 @@ zzhoramin ()
 # Desde: 2008-10-24
 # Licença: GPL
 # Requisitos: zzcarnaval zzdata zzdiadasemana
+# Tags: data
 # ----------------------------------------------------------------------------
 zzhorariodeverao ()
 {
@@ -2945,12 +3001,8 @@ zzhorariodeverao ()
 	# Se o ano não for informado, usa o atual
 	test -z "$ano" && ano=$(date +%Y)
 
-	# Verificação básica
-	if ! zztool testa_ano $ano
-	then
-		echo "Ano inválido '$ano'"
-		return 1
-	fi
+	# Validação
+	zztool -e testa_ano $ano || return 1
 
 	# Só de 2008 em diante...
 	if test $ano -lt 2008
@@ -3080,6 +3132,7 @@ zzjuntalinhas ()
 #
 # Autor: Aurélio Marinho Jargas, www.aurelio.net
 # Desde: 2000-04-24
+# Versão: 2
 # Licença: GPL
 # ----------------------------------------------------------------------------
 zzlimpalixo ()
@@ -3096,11 +3149,10 @@ zzlimpalixo ()
 	esac
 
 	# Remove comentários e linhas em branco
-	cat "${@:--}" |
-		sed "
-			/^[[:blank:]]*$comentario/ d
-			/^[[:blank:]]*$/ d" |
-		uniq
+	sed "
+		/^[[:blank:]]*$comentario/ d
+		/^[[:blank:]]*$/ d" "$@" |
+	uniq
 }
 # ----------------------------------------------------------------------------
 # zzlinha
@@ -3115,6 +3167,7 @@ zzlimpalixo ()
 #
 # Autor: Aurélio Marinho Jargas, www.aurelio.net
 # Desde: 2004-12-23
+# Versão: 2
 # Licença: GPL
 # ----------------------------------------------------------------------------
 zzlinha ()
@@ -3129,7 +3182,7 @@ zzlinha ()
 		padrao="$2"
 		shift; shift
 	fi
-	
+
 	# Talvez o $1 é o número da linha desejada?
 	if zztool testa_numero_sinal "$1"
 	then
@@ -3137,30 +3190,33 @@ zzlinha ()
 		shift
 	fi
 
+	# Se informado um ou mais arquivos, eles existem?
+	for arquivo in "$@"
+	do
+	 	zztool arquivo_legivel "$arquivo" || return 1
+	done
+
 	if [ "$n" ]
 	then
 		# Se foi informado um número, mostra essa linha.
-		# Nota: Suporte a múltiplos arquivos e entrada padrão (STDIN)
+		# Nota: Suporte a múltiplos arquivos ou entrada padrão (STDIN)
 		for arquivo in "${@:--}"
 		do
-			# O arquivo existe?
-			zztool arquivo_legivel "$arquivo" || continue
-			
-			if [ "$n" -lt 0 ]
-			then
-				tail -n ${n#-} "$arquivo" | sed 1q
-			else
-				sed -n ${n}p "$arquivo"
-			fi
+			# Usando cat para ler do arquivo ou da STDIN
+			cat "$arquivo" |
+				if [ "$n" -lt 0 ]
+				then
+					tail -n ${n#-} | sed 1q
+				else
+					sed -n ${n}p
+				fi
 		done
 	else
-		# TODO: usar zztool multi_stdin e arquivo_legivel
-		
 		# Se foi informado um padrão (ou nenhum argumento),
 		# primeiro grepa as linhas, depois mostra uma linha
 		# aleatória deste resultado.
 		# Nota: Suporte a múltiplos arquivos e entrada padrão (STDIN)
-		resultado=$(grep -h -i -- "${padrao:-.}" "${@:--}")
+		resultado=$(zztool file_stdin "$@" | grep -h -i -- "${padrao:-.}")
 		num_linhas=$(echo "$resultado" | sed -n '$=')
 		n=$(( (RANDOM % num_linhas) + 1))
 		[ $n -eq 0 ] && n=1
@@ -4275,6 +4331,7 @@ zzminusculas ()
 # Autor: Aurélio Marinho Jargas, www.aurelio.net
 # Desde: 2008-10-23
 # Licença: GPL
+# Tags: data
 # ----------------------------------------------------------------------------
 zzpascoa ()
 {
@@ -4286,12 +4343,8 @@ zzpascoa ()
 	# Se o ano não for informado, usa o atual
 	test -z "$ano" && ano=$(date +%Y)
 
-	# Verificação básica
-	if ! zztool testa_ano $ano
-	then
-		echo "Ano inválido '$ano'"
-		return 1
-	fi
+	# Validação
+	zztool -e testa_ano $ano || return 1
 
 	# Algoritmo de Jean Baptiste Joseph Delambre (1749-1822)
 	# conforme citado em http://www.ghiorzi.org/portug2.htm
@@ -4584,11 +4637,7 @@ zzsenha ()
 	[ "$1" ] && n=$1
 	
 	# Foi passado um número mesmo?
-	if ! zztool testa_numero "$n"
-	then
-		echo "Número inválido '$n'"
-		return 1
-	fi
+	zztool -e testa_numero "$n" || return 1
 
 	# Já que não repete as letras, temos uma limitação de tamanho
 	maximo=${#lista}
@@ -4666,13 +4715,12 @@ zzseq ()
 	[ "$3" ] && inicio=$1 passo=$2 fim=$3
 
 	# Verificações básicas
-	if ! (
-		zztool testa_numero_sinal "$inicio" &&
-		zztool testa_numero_sinal "$passo" &&
-		zztool testa_numero_sinal "$fim" &&
-		test $passo -ne 0)
+	zztool -e testa_numero_sinal "$inicio" || return 1
+	zztool -e testa_numero_sinal "$passo"  || return 1
+	zztool -e testa_numero_sinal "$fim"    || return 1
+	if test $passo -eq 0
 	then
-		zztool uso seq
+		echo "O passo não pode ser zero."
 		return 1
 	fi
 	
@@ -4709,6 +4757,7 @@ zzseq ()
 # Desde: 2008-11-21
 # Licença: GPL
 # Requisitos: zzdata zzpascoa
+# Tags: data
 # ----------------------------------------------------------------------------
 zzsextapaixao ()
 {
@@ -4719,12 +4768,8 @@ zzsextapaixao ()
 	# Se o ano não for informado, usa o atual
 	test -z "$ano" && ano=$(date +%Y)
 
-	# Verificação básica
-	if ! zztool testa_ano $ano
-	then
-		echo "Ano inválido '$ano'"
-		return 1
-	fi
+	# Validação
+	zztool -e testa_ano $ano || return 1
 
 	# Ah, como é fácil quando se tem as ferramentas certas ;)
 	# e quando já temos o código e só precisamos mudar os numeros
@@ -4748,8 +4793,8 @@ zzshuffle ()
 
 	local linha
 
-	# Suporte a múltiplos arquivos (cat $@) e entrada padrão (cat -)
-	cat "${@:--}" |
+	# Arquivos via STDIN ou argumentos
+	zztool file_stdin "$@" |
 	
 		# Um número aleatório é colocado no início de cada linha,
 		# depois o sort ordena numericamente, bagunçando a ordem
